springdoc:
  api-docs:
    path: /openapi

server:
  port: 4000

spring:
  datasource:
    url: jdbc:h2:mem:bookingdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG